### PR TITLE
Adds support for reading .vue files style tags

### PR DESCRIPTION
**Pull request by jdtjenkins**
Now the style linter will read though a projects' .vue files in search of bad styles.

### CODE REVIEW

**Comment by samturrell** [comment]
Bae. Conflict tho

**Comment by rowbi-wan** [comment]
@jdtjenkins is there anything that needs adding/changing to the readme?

**Comment by samturrell** [comment]
No logo again kiddo

**Comment by rowbi-wan** [comment]
@samturrell i told him not to as it would create merge conflicts with PRs that have the logo

**Review by rowbi-wan — APPROVED** [review]

**Pull request merged**
