### PR TITLE
Generate readme

### PR DESCRIPTION
**Pull request by samturrell**
This PR adds a command to generate the readme made up of individual rule readmes. This will still cause conflicts with PRs, but simply needs the command to be ran again to resolve.

It can be generated by running `npm run generate` in the terminal.

This command is also ran as a pre-commit hook using husky so as long as your base branch is up to date you shouldn't have any conflicts with master.

Bear in mind that this command now uses a template to generate the main readme, so we should never manually modify this file by hand. Instead modify the template located in `build/README.md`.

@netsells/frontend - Please review

### CODE REVIEW

**Comment by rowbi-wan** [comment]
nice.

Considered something along these lines but wasn't happy about the potential merge conflicts. shame we cant have a readme.php

**Comment by samturrell** [comment]
Yeah, never going to be perfect, but at least it's an automated solution for the most part. In the future when it gets too long we can change this to link off to the rule readmes themselves instead of pulling in the whole content so that you can resolve conflicts in the github editor. But should be fine for now.

**Comment by samturrell** [comment]
I may also be keen on splitting the readme out into a README.md for the rule, and  correct.css and incorrect.css files for each rule that we can then pull in to ensure things are standardised even further. Thoughts?

**Comment by rowbi-wan** [comment]
I think you're so preoccupied with whether you could, you haven't stopped to think if you should....🦖

**Comment by samturrell** [comment]
I'm just thinking for things like this https://github.com/netsells/stylelint-config-netsells/pull/11/files/113e87b50bcc8db6dfa90bc9c5247eae9e0edc20#r172018572

**Comment by rowbi-wan** [comment]
good point. want to do it as part of this PR?

**Comment by samturrell** [comment]
Sure

**Comment by samturrell** [comment]
@rowancollins89 - how's that?

**Comment by rowbi-wan** [comment]
looking good Tuz

**Pull request merged**
