### PR TITLE
Color name rule

### PR DESCRIPTION
**Pull request by martin91s**
## Suggested rule/changes(s):
* `<color-named>` : `severity: WARNING`

## Reason for addition/amendment
color's shouldn't be named in your code. e.g 
```
h1 {
    color: red;
}
```
Instead we should primarily be using variables or HEX codes. e.g 
```
h1 {
    color: @red;
}
h1 {
    color: #ff0000;
}
```

@netsells/frontend - Please review

### CODE REVIEW

**Comment by rowbi-wan** [comment]
think i Might be the odd one out here, but I prefer using `white` and `black` instead of the hex values.

**Comment by BeccaAnderton** [comment]
I'm on team @martin91s for this one (unsurprisingly). No colour names pls.

**Comment by rowbi-wan** [comment]
so we'd use 
```css
$white: #fff;

body {
    color: $white;
}
```

rather than 

```css
body {
    color: white;
}
```

seems like we're writing 14 extra characters just for the hell of it......

**Comment by BeccaAnderton** [comment]
Or.... here's an idea, you could just use 

`body { color: #ffffff; }`

Just throwing that out there

**Comment by rowbi-wan** [comment]
true, but as I'm living in a dream world, I'd rather not use any hex values anywhere apart from in the variables.

**Comment by samturrell** [comment]
I'm of the mindset that white should never be a variable as it's a constant. You're then making the less parser do a find and replace for no reason.

**Pull request merged**
